extend type Query {
  listUsers: listUsersResponse @resolver(name: "users/list")
  getUserById(id: ID!): User @resolver(name: "users/get")

  listServiceProviders: listServiceProvidersResponse @resolver(name: "serviceProviders/list")
  getServiceProviderById(id: ID!): ServiceProvider @resolver(name: "serviceProviders/get")

  listServices: listServicesResponse @resolver(name: "services/list")
  getServiceById(id: ID!): Service @resolver(name: "services/get")

  listReviews: listReviewsResponse @resolver(name: "reviews/list")
  getReviewById(id: ID!): Review @resolver(name: "reviews/get")

  listBookings: listBookingsResponse @resolver(name: "bookings/list")
  getBookingById(id: ID!): Booking @resolver(name: "bookings/get")

  listServiceCategories: listServiceCategoriesResponse @resolver(name: "serviceCategories/list")
  getServiceCategoryById(id: ID!): ServiceCategory @resolver(name: "serviceCategories/get")

  listConversations: listConversationsResponse @resolver(name: "conversations/list")
  getConversationById(id: ID!): Conversation @resolver(name: "conversations/get")

  listMessages: listMessagesResponse @resolver(name: "messages/list")
  getMessagesByConversationId(conversationId: ID!): [Message] @resolver(name: "messages/getByConversation")
}
