env:
-   variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: "AIzaSyB_sBCgjt34BNXD2dERtB4ytRGHnOAHMy0"
    availability:
      -   BUILD
      -   RUNTIME
-   variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: "beauty-book-14zko.firebaseapp.com"
    availability:
      -   BUILD
      -   RUNTIME
-   variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: "beauty-book-14zko"
    availability:
      -   BUILD
      -   RUNTIME
-   variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: "beauty-book-14zko.firebasestorage.app"
    availability:
      -   BUILD
      -   RUNTIME
-   variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "630156061433"
    availability:
      -   BUILD
      -   RUNTIME
-   variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: "1:630156061433:web:21984ef8e1f42f31111028"
    availability:
      -   BUILD
      -   RUNTIME
