// dataconnect/schema/booking.gql
import { Timestamp, UUID } from "../../../dataconnect.config";

type Booking @table(name: "bookings", key: "id") {
  id: UUID!
  providerId: UUID!
  providerName: String!
  serviceIds: [String]!
  date: Timestamp!
  status: String!
  clientName: String
  isPaid: Boolean!
  reviewId: String
}

extend type Mutation {
  insertBooking(
    id: UUID!
    providerId: UUID!
    providerName: String!
    serviceIds: [String]!
    date: Timestamp!
    status: String!
    clientName: String
    isPaid: Boolean!
  ): Booking
}
