extend type Query {
  listMessages: listMessagesResponse
  getMessagesByConversationId(conversationId: ID!): [Message]
}

extend type Mutation {
  insertMessage(
    conversationId: ID!
    sender: String!
    text: String!
    isAi: Boolean
    bookingId: String
  ): Message
}

type listMessagesResponse {
  message: [Message]
}
