
type Notification @table {
  id: String! @id
  userId: String!
  icon: String!
  title: String!
  description: String!
  isRead: Boolean!
  bookingId: String
  providerId: String
  createdAt: Timestamp
}
