type Notification @table(key: "id") {
  id: Int!
  icon: String!
  title: String!
  description: String!
  time: String!
  read: Boolean!
  bookingId: String
  providerId: String
}

extend type Query {
  listNotifications: [Notification!]
}
