
"""
A review of a service provider.
"""
type Review @table(name: "reviews") {
  id: ID!
  bookingId: ID!
  author: String!
  avatarUrl: String
  dataAiHint: String
  rating: Float!
  comment: String!
  title: String
}
