# Describes the data available to Data Connect.
# Learn more at https://firebase.google.com/docs/data-connect/graphql-schema

# Every query and mutation is defined in a GQL file. The GQL files are
# combined to create a single schema.
# Learn more at https://firebase.google.com/docs/data-connect/how-to-define-schema#organizing_your_schema
type Query {
  listUsers: [User]
  listServiceProviders: [ServiceProvider]
  listServices: [Service]
  listBookings: [Booking]
  listReviews: [Review]
}

type Mutation {
  insertUser(
    id: String!
    name: String!
    email: String!
    role: String!
  ): User!
}
