extend type Query {
  listServiceCategories: listServiceCategoriesResponse
  getServiceCategoryById(id: ID!): ServiceCategory
}

extend type Mutation {
  insertServiceCategory(name: String!): ServiceCategory
}

type listServiceCategoriesResponse {
  servicecategory: [ServiceCategory]
}
