extend type Query {
  listServices: listServicesResponse
  getServiceById(id: ID!): Service
}

extend type Mutation {
  insertService(
    categoryId: ID!
    name: String!
    description: String!
    price: Float!
    duration: Int!
  ): Service
}

type listServicesResponse {
  services: [Service]
}
