type ServiceProvider @table(key: "id") {
  id: ID!
  userId: String!
  name: String!
  specialty: String!
  avatarUrl: String!
  dataAiHint: String
  rating: Float!
  reviewCount: Int!
  isFeatured: Boolean
  isFavourite: Boolean
  bio: String!
  location: String!
  playlist: String!
}

extend type Query {
  listServiceProviders: [ServiceProvider!]
}
