
"""
Extends the base Query type with service-related queries.
"""
extend type Query {
  """
  Retrieves a list of all services.
  """
  listServices: [Service!] @connector(name: "default-connector")
}
