extend type Query {
  listServiceCategories: listServiceCategoriesResponse
  getServiceCategoryById(id: ID!): ServiceCategory
}

type listServiceCategoriesResponse {
  serviceCategory: [ServiceCategory]
}
