
"""
An application user.
"""
type User @table(name: "users") {
  id: ID!
  name: String!
  email: String! @unique
  role: String!
  provider: ServiceProvider @oneToMany(field: "userId")
}

type Mutation {
    insertUser(id: ID!, name: String!, email: String!, role: String!): User! @resolver(name: "user/insertUser")
}
